# Generated by Django 6.0.2 on 2026-06-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='created_at',
        ),
    ]
