# Generated by Django 6.0.2 on 2026-06-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_shorturl_clicks_shorturl_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.TextField(),
        ),
    ]
