# Generated by Django 6.0.2 on 2026-06-22 03:33

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_remove_shorturl_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(),
        ),
    ]
