# Generated by Django 6.0.2 on 2026-06-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0006_alter_shorturl_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='created_at',
        ),
    ]
